/** Totalitarian cookie banner, 3,000 fictional partners, biscotti, and the load-bearing error. */
import type { CopyRecord } from '../types';

export const banner = {
  kicker: 'FORM DRV-C · COOKIE COMPLIANCE',
  title: '🍪 This website uses cookies.',
  body: [
    'Oatmeal raisin, mostly. We’re sorry. They were on sale.',
    'By continuing to exist within approximately 15 feet of this website, you consent to biometric, telemetric and emotional monitoring by our 3,000 fictional data partners, each of whom has a legitimate interest in you and none of whom exist.*',
  ],
  footnote:
    '*This site sets no cookies and runs no tracking. The real details are on the Legally Binding Vibes page. This banner exists because industry tradition requires one.',
  acceptAll: 'Accept All Cookies, Extended Liabilities, and Spiritual Surrender',
  acceptCookiesAll: 'Accept Cookies (All)',
  manage: 'Manage Detailed Settings',
  reject: 'Reject All',
  rejectLabels: ['Reject… all?', 'Fine. Reject All'],
  close: 'Close',
  regionLabel: 'Cookie compliance (parody)',
};

export const receipts = {
  accept: {
    title: 'CONSENT CERTIFICATE',
    lines: [
      'Cookies accepted: all (conceptually)',
      'Liabilities extended: yes',
      'Spiritual surrender: pending paperwork',
      'Actual cookies set: 0',
      'Choice transmitted: no',
      'Stored on your device: ONE (1) boolean. We felt bad about it.',
    ],
  },
  reject: {
    title: 'REJECTION NOTICE',
    lines: [
      'The cookies have been informed. Their representative has requested a meeting.',
      'Actual cookies set: 0. Actual cookies rejected: 0. Feelings hurt: several.',
    ],
  },
  managed: {
    title: 'PREFERENCE RECEIPT',
    lines: [
      'Preferences saved.',
      'Preferences applied to: nothing.',
      'Preferences respected: deeply.',
    ],
  },
};

export type CategoryId = 'necessary' | 'protein' | 'fortune' | 'biscotti' | 'oatmeal';

export const categories: {
  id: CategoryId;
  name: string;
  icon: string;
  description: string;
  locked?: boolean;
  on: string;
  off: string;
}[] = [
  {
    id: 'necessary',
    name: 'Strictly Necessary Chocolate Chip',
    icon: 'cookie',
    description: 'Required for the structural integrity of the cookie metaphor.',
    locked: true,
    on: 'This cookie cannot be disabled. It has tenure.',
    off: 'This cookie cannot be disabled. It has tenure.',
  },
  {
    id: 'protein',
    name: 'Performance Protein Cookie',
    icon: 'flexed-biceps',
    description: 'Optimized for recruiters who describe themselves as high-performance.',
    on: 'Macros: 30 g protein, 0 g joy.',
    off: 'Macros: 0 g protein, full joy.',
  },
  {
    id: 'fortune',
    name: 'Targeting Fortune Cookie',
    icon: 'fortune-cookie',
    description: 'Predicts that your hiring timeline will be revised.',
    on: '',
    off: 'Fortune withheld. The future is now untargeted.',
  },
  {
    id: 'biscotti',
    name: 'Third-Party Biscotti',
    icon: 'cookie',
    description: 'Provided by a department we have never met.',
    on: 'Vendor: Biscotti Brothers International. Relationship: complicated.',
    off: 'Biscotti Brothers International has been asked to leave. They are still here.',
  },
  {
    id: 'oatmeal',
    name: 'Legacy Oatmeal Raisin',
    icon: 'cookie',
    description: 'Maintained for backward disappointment.',
    on: 'Oatmeal raisin remains, as it always has.',
    off: 'Oatmeal raisin has been disappointed further.',
  },
];

export const fortunes = [
  'You will schedule a call, then reschedule it.',
  'A great candidate is closer than your ATS thinks.',
  'Your req will be approved in Q3. Which year: unspecified.',
  'Beware the culture-fit interview. It is a vibes check.',
  'You will read a résumé all the way to the bottom. Today.',
];

export interface NamedPartner extends CopyRecord {
  name: string;
  purpose: string;
  detail?: string;
  lockedOff?: boolean;
}

export const namedPartners: NamedPartner[] = [
  {
    id: 'david-analytics',
    name: 'DAVID ANALYTICS',
    purpose: 'Determining whether you are presently on this website.',
    detail: 'Status: disabled because that would be stupid.',
    lockedOff: true,
    status: 'fictional',
    text: 'DAVID ANALYTICS',
  },
  {
    id: 'big-resume',
    name: 'BIG RÉSUMÉ',
    purpose: 'Synergistic résumé optimization.',
    detail: 'Legal basis: vibes.',
    status: 'fictional',
    text: 'BIG RÉSUMÉ',
  },
  {
    id: 'cabbage',
    name: 'NICOLAS CABBAGE',
    purpose: 'Legitimate vegetable interest.',
    status: 'fictional',
    text: 'NICOLAS CABBAGE',
  },
  {
    id: 'algorithm',
    name: 'THE ALGORITHM',
    purpose: 'Knows what it did.',
    status: 'fictional',
    text: 'THE ALGORITHM',
  },
  {
    id: 'doug',
    name: 'DOUG’S BASEMENT CLOUD',
    purpose: 'The cloud. Hosting provider: Doug.',
    detail: 'Doug is tired.',
    status: 'fictional',
    text: 'DOUG’S BASEMENT CLOUD',
  },
  {
    id: 'process-builder',
    name: 'A PROCESS BUILDER THAT KNOWS WHAT IT DID',
    purpose: 'Order of execution.',
    detail: 'Status: migrated to Flow.',
    status: 'verified',
    blockRefs: ['A3'],
    text: 'A PROCESS BUILDER THAT KNOWS WHAT IT DID. Status: migrated to Flow.',
  },
];

export const vendorWords = {
  adjectives: [
    'Synergistic',
    'Holistic',
    'Agile',
    'Frictionless',
    'Legacy',
    'Bespoke',
    'Omnichannel',
    'Proactive',
    'Cloud-Native',
    'Artisanal',
    'Hyperlocal',
    'Quantum',
    'Scalable',
    'Mission-Critical',
    'Best-of-Breed',
    'Enterprise',
    'Decentralized',
    'Gluten-Free',
    'Carbon-Neutral',
    'Seamless',
    'Disruptive',
    'Heritage',
    'Premium',
    'Boutique',
    'Integrated',
    'Blockchain-Adjacent',
    'Vertically Integrated',
    'Mindful',
    'Predictive',
    'Real-Time',
    'Low-Code',
    'Headless',
    'Serverless',
    'Zero-Trust',
    'Farm-to-Table',
    'Data-Driven',
    'Evergreen',
    'Streamlined',
    'Next-Gen',
    'Certified',
  ],
  nouns: [
    'Biscuit',
    'Crumb',
    'Oat',
    'Wafer',
    'Macaron',
    'Snickerdoodle',
    'Shortbread',
    'Graham',
    'Gingersnap',
    'Madeleine',
    'Scone',
    'Pretzel',
    'Cracker',
    'Bagel',
    'Muffin',
    'Strudel',
    'Brioche',
    'Crouton',
    'Pastry',
    'Waffle',
    'Churro',
    'Truffle',
    'Nougat',
    'Toffee',
    'Praline',
    'Meringue',
    'Biscotto',
    'Fig Bar',
    'Rice Cake',
    'Pita',
    'Crumpet',
    'Tortilla',
    'Cannoli',
    'Éclair',
    'Danish',
    'Bundt',
    'Tart',
    'Cobbler',
    'Crêpe',
    'Donut',
  ],
  suffixes: [
    'Holdings LLC',
    'Analytics',
    'Partners',
    'Labs',
    'Group',
    '& Sons',
    'Collective',
    'Consortium',
    'Intelligence',
    'Solutions',
    'Worldwide',
    'Syndicate',
  ],
  purposes: [
    'Measuring your cursor’s emotional state',
    'Determining whether you blinked',
    'Cross-referencing your vibe with your LinkedIn vibe',
    'Legitimate interest in your lunch',
    'Predicting your next tab',
    'Estimating your patience in milliseconds',
    'Optimizing synergy (undefined)',
    'Monitoring your posture (poor)',
    'Tracking your cookie crumbs',
    'Detecting sarcasm (fails)',
    'Assessing culture fit via font preference',
    'Counting your scrolls for no reason',
    'Selling your silence back to you',
    'Auditing your tab count (concerning)',
    'Inferring your coffee order',
    'Benchmarking your sighs',
    'Enriching your data with artisanal nonsense',
    'Remembering you forgot something',
    'Measuring how long you’ve been on hold emotionally',
    'Nothing. This vendor just likes to be included.',
  ],
};

export const vendorsDialog = {
  title: 'Manage 3,000 Fictional Partners',
  closeLabel: 'Close partner settings',
  categoriesHeading: 'Cookie categories',
  partnersHeading: 'Partners',
  page: (n: number, total: number) => `Page ${n} of ${total}`,
  prev: '‹ Prev',
  next: 'Next ›',
  jump: 'Jump to page',
  reset: 'Reset',
  resetToast: 'All 3,000 partners have been re-enabled. They never left.',
  biscottiButton: 'Accept all biscotti',
  save: 'Save & close',
  close: 'Close',
  footer:
    'No tracking preferences were changed. No choice was transmitted. These switches are connected to nothing, which is the most honest thing about them.',
};

export const biscotti = {
  receipt:
    'Fifty (50) biscotti have been stored on your device under uvcr:biscotti. They are drawings. They cannot track you. They can barely stand up.',
  view: 'View them',
  remove: 'Remove them',
  removed: 'The biscotti have been removed. They left quietly.',
  names: [
    'Gerald',
    'Linda',
    'Kevin (not the planet)',
    'Crumbs McGee',
    'Sir Dunksalot',
    'Biscuit Bismarck',
    'Deborah',
    'The Twins',
    'Oatis',
    'Raisin Cane',
    'Chip',
    'Dale',
    'Marge',
    'Snickers (no relation)',
    'Brenda',
    'Old Greg’s Cousin',
    'Toast (misfiled)',
    'Pam',
    'Gary',
    'Waffles',
    'Doughbert',
    'Crumbelina',
    'Nibbles',
    'Barb',
    'Walter',
    'Cookie Monsterrat',
    'Sprinkles',
    'Hank',
    'Lorna',
    'Morsel',
    'Tim',
    'Dough Jones',
    'Bisco Diaz',
    'Carl',
    'Sheila',
    'Scone Connery',
    'Muffin Top',
    'Glenda',
    'Crispin',
    'Dorothy',
    'Bartholomew',
    'Fudge Judy',
    'Paul',
    'Gingerly',
    'Yolanda',
    'Dunk Hank',
    'Crumb Hemsworth',
    'Mabel',
    'Sugar Ray',
    'Final Biscotto',
  ],
  kinds: {
    'chocolate chip': [
      '   .-""""-.',
      '  / o   o  \\',
      ' |  o  o  o |',
      '  \\  o   o /',
      "   `-....-'",
    ],
    biscotti: ['  ____________', ' /  .  :  .  /|', '/____________/ |', '|  .  :  .  |/'],
    fortune: ['   ___', ' /  _  \\', '( (  ) )-- "hire him"', ' \\_\\_/_/'],
    'oatmeal raisin': [
      '   .-~~~~-.',
      '  / r . r  \\',
      ' | .  r  .  |',
      '  \\ r . r  /',
      "   '-....-'   (sorry)",
    ],
    shortbread: [' ,----------.', ' | :  :  :  |', ' | :  :  :  |', " '----------'"],
    snickerdoodle: ['   .-~~-.', '  ( * .* )', "   '-..-'"],
  } as Record<string, string[]>,
};

export const loadBearing = {
  title: 'CRITICAL ERROR: The cookie banner was load-bearing.',
  body: 'Structural dependency discovered. Removing #cookie-consent-overlay has compromised the Department’s ability to pretend it needs your consent. Facilities has been notified. (Facilities is a MutationObserver.)',
  restore: 'Restore banner',
  dismiss: 'Dismiss (at your own risk)',
  fine: 'This is not security. You can delete anything you like. It’s your browser.',
};
