/** Independent Character Review — main cards and the appendix the committee asked us to remove. */
import type { CopyRecord } from '../types';

export interface Flag extends CopyRecord {
  /** `text` is the claim. */
  evidence: string;
  reviewer: string;
  stamp: string;
  tone: 'green' | 'amber' | 'red' | 'ink';
  /** Personal claims David should veto if false (surfaced in the PR). */
  personalClaim?: boolean;
}

export const aboutCopy = {
  kicker: 'FORM DRV-3 · INDEPENDENT CHARACTER REVIEW',
  h1: 'Green Flags',
  sub: 'Independently unverified. Aggressively self-reported.',
  reviewer: 'Office of Candidate Self-Assessment, chaired by the candidate.',
  stampHint: 'Select a stamp to read the evidence.',
  evidenceLabel: 'Evidence',
  reviewerLabel: 'Reviewer note',
  groundedLabel: 'Grounded in',
  appendixSummary: (n: number) => `Appendix the committee asked us to remove (${n} items)`,
  appendixIntro:
    'The committee voted to remove the following findings. The committee was outvoted by the candidate, who is also the committee.',
  appendixLabel: 'FICTIONAL AUDIT · SELF-REPORTED',
};

export const flags: Flag[] = [
  {
    id: 'prod',
    text: 'Has never intentionally dropped production.',
    evidence: 'The adverb is important.',
    reviewer: 'Adverb verified.',
    stamp: 'Technically compliant',
    tone: 'amber',
    status: 'fictional',
  },
  {
    id: 'git',
    text: 'Understands Git within professionally acceptable tolerances.',
    evidence: 'Tolerances available upon request.',
    reviewer: 'Request pending.',
    stamp: 'Provisionally green',
    tone: 'green',
    status: 'fictional',
  },
  {
    id: 'carts',
    text: 'Returns shopping carts.',
    evidence: 'Even when no one is watching. Especially when no one is watching.',
    reviewer: 'Someone is always watching.',
    stamp: 'Reviewed by the candidate',
    tone: 'ink',
    status: 'fictional',
    personalClaim: true,
  },
  {
    id: 'dns',
    text: 'Can admit when DNS was the problem.',
    evidence: 'It is always DNS.',
    reviewer: 'The appeals process remains open.',
    stamp: 'Provisionally green',
    tone: 'green',
    status: 'fictional',
  },
  {
    id: 'semicolon',
    text: 'Has never caused an international incident through a missing semicolon.',
    evidence: 'Writes Python.',
    reviewer: 'Loophole acknowledged.',
    stamp: 'Technically compliant',
    tone: 'amber',
    status: 'fictional',
  },
  {
    id: 'server-room',
    text: 'Can be left unsupervised in a server room.',
    evidence: 'Has been. Came back out.',
    reviewer: 'Server room also fine.',
    stamp: 'Provisionally green',
    tone: 'green',
    status: 'fictional',
  },
  {
    id: 'workstations',
    text: 'Deployed 150+ workstations and never once read anyone’s security questions aloud at a party.',
    evidence: 'Imaging automated with PowerShell.',
    reviewer: 'Parties attended: undisclosed.',
    stamp: 'Verified (partially)',
    tone: 'green',
    status: 'verified',
    blockRefs: ['B1'],
  },
  {
    id: 'backups',
    text: 'Does not know where the bodies are buried.',
    evidence: 'Knows where the backups are.',
    reviewer: 'Which is worse.',
    stamp: 'Pending context',
    tone: 'amber',
    status: 'fictional',
  },
  {
    id: 'staging',
    text: 'Can distinguish production from staging.',
    evidence: 'Verification method: reads the tab title before panicking.',
    reviewer: 'Colors remain under review.',
    stamp: 'Provisionally green',
    tone: 'green',
    status: 'fictional',
  },
  {
    id: 'secrets',
    text: 'Keeps secrets out of source control.',
    evidence: 'The fictional secrets in this site’s HTML comments are there for artistic reasons.',
    reviewer: 'They are not secrets. They are literature.',
    stamp: 'Technically compliant',
    tone: 'amber',
    status: 'fictional',
  },
  {
    id: 'docs',
    text: 'Writes documentation people could read.',
    evidence: 'Authored an org’s first technical documentation of its data model and integrations.',
    reviewer: 'Someone may have read it.',
    stamp: 'Verified',
    tone: 'green',
    status: 'verified',
    blockRefs: ['A4'],
  },
  {
    id: 'defect',
    text: 'Finds the bug the migration was hiding.',
    evidence:
      'Moved an entire automation inventory to Flow and caught the order-of-execution defect before it caught him.',
    reviewer: 'The defect has been reassigned to history.',
    stamp: 'Verified',
    tone: 'green',
    status: 'verified',
    blockRefs: ['A3'],
  },
  {
    id: 'alibi-outage',
    text: 'Has an alibi for the last major production outage.',
    evidence: 'Logs available upon request.',
    reviewer: 'Logs requested. Logs were fine.',
    stamp: 'Provisionally green',
    tone: 'green',
    status: 'fictional',
  },
  {
    id: 'linux',
    text: 'Uses Linux, but will only mention it every few minutes.',
    evidence: 'Current daily drivers: Ubuntu, Kubuntu, Bazzite, Nobara, Omarchy.',
    reviewer: 'This is normal.',
    stamp: 'Verified',
    tone: 'green',
    status: 'verified',
    blockRefs: ['SK-linux'],
  },
  {
    id: 'vac',
    text: 'Has never been VAC banned.',
    evidence: 'Has been accused.',
    reviewer: 'Considered it a compliment.',
    stamp: 'Self-reported',
    tone: 'ink',
    status: 'fictional',
    personalClaim: true,
  },
  {
    id: 'emergency',
    text: 'Has an emergency contact.',
    evidence: 'The emergency contact has an emergency contact.',
    reviewer: 'We don’t talk about why.',
    stamp: 'Pending context',
    tone: 'amber',
    status: 'fictional',
    personalClaim: true,
  },
  {
    id: 'stream-deck',
    text: 'Brought a Stream Deck up on Linux without vendor software.',
    evidence:
      'Diagnosed the enumeration failure by comparing two open-source host implementations.',
    reviewer: 'The vendor was not consulted. The vendor was not needed.',
    stamp: 'Verified',
    tone: 'green',
    status: 'verified',
    blockRefs: ['P2'],
  },
  {
    id: 'background',
    text: 'Passed every background check he’s been given.',
    evidence: 'And a few he administered to himself.',
    reviewer: 'Self-administered results: suspiciously good.',
    stamp: 'Self-reported',
    tone: 'ink',
    status: 'fictional',
    personalClaim: true,
  },
];

export const appendix: Flag[] = [
  {
    id: 'killed',
    text: 'Has not killed anyone.',
    evidence: 'Verification source: self-reported.',
    reviewer: 'Rafting clients lost: zero (net).',
    stamp: 'Self-reported',
    tone: 'red',
    status: 'verified',
    blockRefs: ['D1'],
  },
  {
    id: 'alibi',
    text: 'Airtight alibi for 9/11.',
    evidence: 'I was one year old, sitting next to my mom in the living room. My mom is my alibi.',
    reviewer: 'Witness credibility: extremely high. Witness bias: also extremely high.',
    stamp: 'Alibi on file',
    tone: 'red',
    status: 'fictional',
    personalClaim: true,
  },
  {
    id: 'warrants',
    text: 'No active warrants in any of the states he’s personally checked.',
    evidence: 'Methodology: vibes.',
    reviewer: 'Remaining states: in progress.',
    stamp: 'Pending context',
    tone: 'red',
    status: 'fictional',
  },
  {
    id: 'restraining',
    text: 'Only one restraining order, and it was against a Process Builder that knew what it did.',
    evidence: 'It has since been migrated to Flow.',
    reviewer: 'Distance maintained: one platform release.',
    stamp: 'Resolved',
    tone: 'red',
    status: 'verified',
    blockRefs: ['A3'],
  },
  {
    id: 'true-crime',
    text: 'Not currently the subject of a true-crime documentary.',
    evidence: 'Pre-production doesn’t count.',
    reviewer: 'Working title withheld.',
    stamp: 'Pending context',
    tone: 'red',
    status: 'fictional',
  },
  {
    id: 'non-homicide',
    text: 'Unbroken non-homicide record.',
    evidence:
      'A 100% success rate in refraining from capital felonies, manslaughter and international maritime piracy across all employment periods.',
    reviewer: 'Piracy clause added after an incident with a raft.',
    stamp: 'Technically compliant',
    tone: 'red',
    status: 'fictional',
  },
  {
    id: 'interpol',
    text: 'Zero active extraditions or INTERPOL red notices in all jurisdictions party to the 1988 Vienna Convention.',
    evidence: 'The treaty reference is decorative.',
    reviewer: 'Decoration approved.',
    stamp: 'Decorative',
    tone: 'red',
    status: 'fictional',
  },
  {
    id: 'oxygen',
    text: 'Maintains resting blood oxygen above 94% during production outages without pulmonary assistance.',
    evidence: 'Not medical advice. Not a performance metric. Barely a sentence.',
    reviewer: 'Breathing: ongoing.',
    stamp: 'Self-reported',
    tone: 'red',
    status: 'fictional',
  },
];
