/** Résumé.ppt (Deluxe Edition). The slides reuse the résumé data; only the packaging is loud. */
export const presentationCopy = {
  kicker: 'FORM DRV-25 · PRESENTATION MODE',
  h1: 'Résumé.ppt (Deluxe Edition)',
  sub: 'The same résumé, now with transitions, WordArt and unsolicited enthusiasm.',
  slideLabel: (n: number) => `Slide ${n}`,
  notesLabel: 'Speaker notes',
  titleSlide: { eyebrow: 'A presentation by', subtitle: 'Software Engineer · Broomfield, CO' },
  sections: {
    summary: 'Executive Summary',
    experience: 'Professional Experience',
    projects: 'Special Projects',
    skills: 'Core Competencies',
    education: 'Academic Credentials',
  },
  closing: {
    title: 'Thank You!',
    body: 'Questions? (Please, no questions.)',
    plain: 'Prefer it without the transitions?',
    plainLink: 'Read the plain résumé →',
  },
  sound: { off: 'Transition sounds: off', on: 'Transition sounds: on' },
  adlibs: [
    'KA-POW!',
    'RADICAL!',
    'SYNERGY!!',
    'TUBULAR!',
    'NOW WITH MORE FLOW!',
    'AS SEEN ON LINKEDIN',
    'NEW! IMPROVED!',
    'ALL THAT AND A BAG OF CHIPS',
    'BOOYAH!',
    'OFF THE HOOK!',
    'WOWZERS!',
    'NO WAY!',
    'MAXIMUM EFFORT!',
    'BEST IN SHOW!',
  ],
  notes: [
    'Pause here for applause.',
    'Make eye contact with the recruiter. Not too much.',
    'Gesture confidently at the bullet points.',
    'Do not read the slide out loud. (Read the slide out loud.)',
    'If the projector fails, this is where you tell the rafting story.',
    'Say "synergy" once. Just once.',
    'Click the clicker. Nothing happens. Click it again.',
    'This is the part where you pretend to check the time.',
  ],
};
