/**
 * Asset & license ledger. Every non-code asset shipped by this site is listed here.
 * credits.test.ts fails if a file under public/captcha, public/illustrations, public/cursors or a
 * favicon lacks an entry, and Icon.astro refuses icons that aren't in ICON_MANIFEST.
 */

export type IconSet = 'lucide' | 'fluent' | 'game';

/** The only icons the site may render. Icon.astro throws at build for anything else. */
export const ICON_MANIFEST: Record<IconSet, readonly string[]> = {
  lucide: [
    'x',
    'volume-2',
    'volume-x',
    'printer',
    'download',
    'external-link',
    'rotate-ccw',
    'refresh-cw',
    'skip-forward',
    'sun',
    'moon',
    'moon-star',
    'flashlight',
    'shield-alert',
    'circle-help',
    'check',
    'arrow-right',
    'arrow-left',
    'mail',
    'file-text',
    'play',
    'pause',
    'keyboard',
    'siren',
    'stamp',
    'scale',
    'dices',
    'gauge',
    'bug',
    'terminal',
    'lock',
    'lock-open',
    'eye',
    'eye-off',
    'info',
    'triangle-alert',
    'chevron-down',
    'chevron-right',
    'menu',
  ],
  fluent: [
    'cookie',
    'fortune-cookie',
    'flexed-biceps',
    'leafy-green',
    'receipt',
    'robot',
    'detective',
    'paperclip',
    'slot-machine',
    'game-die',
    'headstone',
    'flashlight',
    'raccoon',
    'goose',
    'penguin',
    'window',
    'sauropod',
    't-rex',
    'full-moon-face',
    'crescent-moon',
    'ringed-planet',
    'round-pushpin',
    'camera',
    'bell',
    'warning',
    'police-car-light',
    'stop-sign',
    'balance-scale',
    'scroll',
    'file-cabinet',
    'clipboard',
    'hourglass-not-done',
    'brain',
    'floppy-disk',
    'desktop-computer',
    'bomb',
    'canoe',
    'water-wave',
    'droplet',
    'magnifying-glass-tilted-left',
    'money-bag',
    'coin',
    'party-popper',
    'crossed-fingers',
    'thinking-face',
    'zany-face',
    'pleading-face',
    'face-holding-back-tears',
    'spiral-calendar',
    'cheese-wedge',
    'wastebasket',
    'ninja',
  ],
  game: [
    'tombstone',
    'crosshair',
    'paddles',
    'cabbage',
    'gavel',
    'stamper',
    'handcuffs',
    'cctv-camera',
    'id-card',
    'poker-hand',
  ],
};

export interface LedgerEntry {
  id: string;
  name: string;
  kind: 'font' | 'icons' | 'original-art' | 'library' | 'media' | 'licensed-photo';
  license: string;
  author: string;
  url?: string;
  /** Files (relative to public/) covered by this entry. */
  files?: readonly string[];
  note?: string;
}

const windows = [
  'house',
  'stained-glass',
  'car',
  'airplane',
  'bay',
  'drive-thru',
  'browser',
  'terminal',
  'opportunity',
];
const cabbages = [
  'sunglasses',
  'bowtie',
  'guard-badge',
  'cape',
  'helmet',
  'fedora-map',
  'goggles',
  'crown',
  'eyebrows',
];

export const LEDGER: LedgerEntry[] = [
  {
    id: 'font-plex-sans',
    name: 'IBM Plex Sans',
    kind: 'font',
    license: 'SIL Open Font License 1.1',
    author: 'IBM (Mike Abbink, Bold Monday)',
    url: 'https://github.com/IBM/plex',
  },
  {
    id: 'font-plex-mono',
    name: 'IBM Plex Mono',
    kind: 'font',
    license: 'SIL Open Font License 1.1',
    author: 'IBM (Mike Abbink, Bold Monday)',
    url: 'https://github.com/IBM/plex',
  },
  {
    id: 'font-fraunces',
    name: 'Fraunces',
    kind: 'font',
    license: 'SIL Open Font License 1.1',
    author: 'Undercase Type (Phaedra Charles, Flavia Zimbardi)',
    url: 'https://github.com/undercasetype/Fraunces',
  },
  {
    id: 'font-comic-neue',
    name: 'Comic Neue',
    kind: 'font',
    license: 'SIL Open Font License 1.1',
    author: 'Craig Rozynski & Hrant Papazian',
    url: 'https://comicneue.com/',
    note: 'The “Light (Comic Sans)” theme uses your own Comic Sans if you have it; it is not shipped here.',
  },
  {
    id: 'icons-lucide',
    name: 'Lucide',
    kind: 'icons',
    license: 'ISC',
    author: 'Lucide Contributors',
    url: 'https://lucide.dev/',
  },
  {
    id: 'icons-fluent',
    name: 'Fluent Emoji (Flat)',
    kind: 'icons',
    license: 'MIT',
    author: 'Microsoft Corporation',
    url: 'https://github.com/microsoft/fluentui-emoji',
  },
  {
    id: 'icons-game',
    name: 'game-icons.net',
    kind: 'icons',
    license: 'CC BY 3.0',
    author: 'game-icons.net contributors (Lorc, Delapouite and others)',
    url: 'https://game-icons.net/',
    note: 'Icons by the game-icons.net contributors, licensed under CC BY 3.0.',
  },
  {
    id: 'art-windows',
    name: 'CAPTCHAN’T™ window illustrations',
    kind: 'original-art',
    license: 'Public domain (Unlicense), like the code',
    author: 'Made for this site',
    files: windows.map((w) => `captcha/windows/${w}.svg`),
  },
  {
    id: 'art-cabbage',
    name: 'Nicolas Cabbage and the legally nervous rectangle',
    kind: 'original-art',
    license: 'Public domain (Unlicense), like the code',
    author: 'Made for this site',
    files: [
      ...cabbages.map((c) => `captcha/cabbage/${c}.svg`),
      'captcha/cabbage/legal-rectangle.svg',
    ],
    note: 'No celebrity likeness is used. No endorsement implied by anyone, including the cabbage.',
  },
  {
    id: 'art-illustrations',
    name: 'Institutional illustrations',
    kind: 'original-art',
    license: 'Public domain (Unlicense), like the code',
    author: 'Made for this site',
    files: [
      'illustrations/human-silhouette.svg',
      'illustrations/tombstone.svg',
      'illustrations/dancer-fallback.svg',
      'illustrations/empty-grid.svg',
      'illustrations/felt-noise.svg',
      'illustrations/paper-noise.svg',
      'illustrations/stamp-ring.svg',
    ],
  },
  {
    id: 'art-favicon',
    name: 'DRV rubber-stamp favicon (and its crying variant)',
    kind: 'original-art',
    license: 'Public domain (Unlicense), like the code',
    author: 'Made for this site',
    files: ['favicon.svg', 'favicon-crying.svg'],
  },
  {
    id: 'art-cursors',
    name: 'Cabbage, paddle and crosshair cursors',
    kind: 'original-art',
    license: 'Public domain (Unlicense), like the code',
    author: 'Made for this site',
    files: ['cursors/cabbage.svg', 'cursors/paddle.svg', 'cursors/crosshair.svg'],
  },
  {
    id: 'lib-astro',
    name: 'Astro',
    kind: 'library',
    license: 'MIT',
    author: 'The Astro Technology Company',
    url: 'https://astro.build/',
  },
  {
    id: 'lib-matter',
    name: 'matter-js',
    kind: 'library',
    license: 'MIT',
    author: 'Liam Brummitt',
    url: 'https://brm.io/matter-js/',
    note: 'Loaded only when you press the button you were told not to press.',
  },
  {
    id: 'media-rick',
    name: 'Rick Astley — official music video',
    kind: 'media',
    license: 'Embedded via YouTube’s privacy-enhanced player; not hosted here',
    author: 'Rick Astley / the rights holders',
    note: 'Loaded only after you click. No lyrics are reproduced on this site.',
  },
];

export const INSPIRATION = [
  'User Inyerface by Bagaar — a frustration machine that ends at a jobs page',
  'Philippe Dubost’s Amazon-listing résumé — total commitment to one metaphor',
  'r/badUIbattles — fully working implementations of terrible ideas',
  'Robby Leonardi’s interactive résumé — the gimmick is the portfolio piece',
  'Bruno Simon’s portfolio — spectacle with a plain-HTML fallback',
];

export const creditsCopy = {
  kicker: 'FORM DRV-13 · CREDITS',
  h1: 'Credits',
  sub: 'Everything here that someone else made, and the licenses they made it under.',
  sections: {
    fonts: 'Fonts',
    icons: 'Icons',
    art: 'Original art',
    libraries: 'Libraries',
    media: 'Media',
    inspiration: 'Inspiration',
  },
  iconsUsed: 'Icons used from this set:',
  footer: 'No endorsement implied by anyone, including the cabbage.',
};
